name: Run Robot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run robot
        run: python organize_data.py

      - name: Commit changes
        run: |
          git config user.name "robot"
          git config user.email "robot@github"
          git add .
          git commit -m "robot run" || echo "no changes"
          git push
